# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lM0kELekES_6wG6JeCMwGHiuu7xQmosK

# main.py
"""

# I imported tkinter so that I could initialize and run the graphical user interface.
import tkinter as tk

from load_dataset_module import DatasetLoader
from query_module import QueryProcessor
from user_interface_module import HealthAnalyticsUI

# I defined a class to manage the application startup process.
class ApplicationStarter:

    # I defined the constructor to initialize the ApplicationStarter object.
    def __init__(self, dataset_path):

        # I stored the dataset path provided by the user.
        self.dataset_path = dataset_path


    # I defined a method to start the application.
    def start_application(self):

        # I used a try block to handle errors during dataset loading and application execution.
        try:

            # I displayed a message indicating that dataset loading had started.
            print("Loading dataset...")

            # I created an instance of DatasetLoader using the provided file path.
            loader_instance = DatasetLoader(self.dataset_path)

            # I called the method to read and process the dataset.
            loaded_data = loader_instance.read_dataset()

            # I checked if any data was loaded successfully.
            if loaded_data:

                # I printed the first record for debugging and verification purposes.
                print("Sample Record:", loaded_data[0])

            # I checked if the dataset was empty or failed to load.
            if not loaded_data:

                # I printed a message indicating failure and stopped execution.
                print("No data was loaded. Application will exit.")

                # I exited the method early to prevent further errors.
                return

            # I printed a success message after dataset loading.
            print("Dataset loaded successfully.")

            # I initialized the main tkinter root window.
            root_window = tk.Tk()

            # I created an instance of the UI application and passed the dataset.
            ui_app = HealthAnalyticsUI(root_window, loaded_data)

            # I started the GUI event loop to make the application interactive.
            root_window.mainloop()

        # I handled the case where the dataset file was not found.
        except FileNotFoundError:

            # I displayed an appropriate error message.
            print("Error: Dataset file not found.")

        # I handled any unexpected runtime errors.
        except Exception as unexpected_error:

            # I printed the error message for debugging.
            print("Application error:", unexpected_error)


# I defined the main entry point of the program.
def main():

    # I specified the dataset file name.
    file_name = "data.csv"

    # I created an instance of the ApplicationStarter class.
    app_runner = ApplicationStarter(file_name)

    # I called the method to start the application.
    app_runner.start_application()


# I checked whether the script was executed directly.
if __name__ == "__main__":

    # I called the main function to launch the application.
    main()