# -*- coding: utf-8 -*-
"""query_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lM0kELekES_6wG6JeCMwGHiuu7xQmosK

# query_module.py
"""

# I imported the csv module so that I could export processed results into CSV files.
import csv

# I imported Counter to efficiently count categorical occurrences such as diet patterns.
from collections import Counter

# I defined a class to handle query-based data processing and analysis.
class QueryProcessor:

    # I defined the constructor to initialize the QueryProcessor object.
    # I accepted the dataset bundle as input for performing queries.
    def __init__(self, dataset_bundle):

        # I stored the dataset records for reuse across all query methods.
        self.dataset_bundle = dataset_bundle

        # I initialized a StatisticalAnalyzer object to reuse statistical computations.
        self.stats_helper = StatisticalAnalyzer(dataset_bundle)

    # I defined a helper method to calculate statistics for age values.
    def _ages_stats(self, age_list):

        # I returned mean, median, and mode using the statistical helper.
        return {
            "mean": self.stats_helper.calculate_mean(age_list),
            "median": self.stats_helper.calculate_median(age_list),
            "mode": self.stats_helper.calculate_mode(age_list)
        }

    # I defined a method to save results into a CSV file.
    def save_to_csv(self, result_data, file_name):

        # I used a try block to handle file writing errors.
        try:

            # I opened the file in write mode and ensured no extra blank lines.
            with open(file_name, mode='w', newline='') as file_obj:

                # I created a CSV writer object.
                writer = csv.writer(file_obj)

                # I checked if the result data was a list.
                if isinstance(result_data, list):

                    # I ensured the list was not empty.
                    if result_data:

                        # I wrote the header row.
                        writer.writerow(result_data[0].keys())

                        # I iterated through each row.
                        for row in result_data:

                            # I wrote each row’s values.
                            writer.writerow(row.values())

                # I checked if the result data was a dictionary.
                elif isinstance(result_data, dict):

                    # I iterated through key-value pairs.
                    for key, value in result_data.items():

                        # I wrote each pair as a row.
                        writer.writerow([key, value])

        # I handled any errors during file writing.
        except Exception as err:

            # I printed an error message for debugging.
            print("Error saving file:", err)

    # I filtered smokers with hypertension and computed age statistics.
    def smokers_with_hypertension(self):

        # I filtered relevant records using list comprehension.
        filtered_group = [
            r for r in self.dataset_bundle
            if r.get("smoking_status") in ["smokes", "formerly smoked"]
            and r.get("hypertension") == 1
        ]

        # I extracted numeric age values.
        ages = [r["age"] for r in filtered_group if isinstance(r.get("age"), (int, float))]

        # I returned age statistics.
        return self._ages_stats(ages)

    # I analyzed patients with heart disease.
    def heart_disease_stats(self):

        # I filtered patients with heart disease.
        selected_group = [r for r in self.dataset_bundle if r.get("heart_disease") == 1]

        # I extracted age values.
        ages = [r["age"] for r in selected_group if isinstance(r.get("age"), (int, float))]

        # I extracted glucose values.
        glucose = [r["average_glucose_level"] for r in selected_group if isinstance(r.get("average_glucose_level"), (int, float))]

        # I calculated age statistics.
        result = self._ages_stats(ages)

        # I added average glucose value.
        result["avg_glucose"] = self.stats_helper.calculate_mean(glucose)

        # I returned the result.
        return result

    # I grouped hypertensive patients by gender and stroke occurrence.
    def gender_hypertension_stroke(self):

        # I initialized a container for grouped data.
        result_container = {}

        # I iterated through dataset records.
        for entry in self.dataset_bundle:

            # I filtered hypertensive patients.
            if entry.get("hypertension") == 1:

                # I extracted gender.
                gender_key = entry.get("gender")

                # I extracted stroke status.
                stroke_flag = entry.get("stroke_occurrence")

                # I created a grouping key.
                key_name = f"{gender_key}_stroke_{stroke_flag}"

                # I initialized list if key not present.
                if key_name not in result_container:
                    result_container[key_name] = []

                # I checked if age was numeric.
                if isinstance(entry.get("age"), (int, float)):

                    # I appended age to group.
                    result_container[key_name].append(entry["age"])

        # I returned computed statistics for each group.
        return {k: self._ages_stats(v) for k, v in result_container.items()}

    # I grouped data based on physical activity.
    def activity_based_stats(self):

        # I initialized dictionary for activity groups.
        activity_groups = {}

        # I iterated through dataset.
        for record in self.dataset_bundle:

            # I extracted activity type.
            activity = record.get("physical_activity")

            # I initialized group if not present.
            if activity not in activity_groups:
                activity_groups[activity] = {"bmi": [], "glucose": [], "risk": []}

            # I appended BMI if numeric.
            if isinstance(record.get("bmi"), (int, float)):
                activity_groups[activity]["bmi"].append(record["bmi"])

            # I appended glucose if numeric.
            if isinstance(record.get("average_glucose_level"), (int, float)):
                activity_groups[activity]["glucose"].append(record["average_glucose_level"])

            # I appended risk score if numeric.
            if isinstance(record.get("stroke_risk_score"), (int, float)):
                activity_groups[activity]["risk"].append(record["stroke_risk_score"])

        # I returned computed averages.
        return {
            act: {
                "avg_bmi": self.stats_helper.calculate_mean(vals["bmi"]),
                "avg_glucose": self.stats_helper.calculate_mean(vals["glucose"]),
                "avg_risk": self.stats_helper.calculate_mean(vals["risk"])
            }
            for act, vals in activity_groups.items()
        }

    # I compared stroke cases between urban and rural areas.
    def urban_rural_stroke(self):

        # I initialized location groups.
        location_group = {"urban": [], "rural": []}

        # I iterated through dataset.
        for rec in self.dataset_bundle:

            # I filtered stroke cases.
            if rec.get("stroke_occurrence") == 1:

                # I extracted residence type.
                loc = rec.get("residence_type")

                # I checked valid location and numeric age.
                if loc in location_group and isinstance(rec.get("age"), (int, float)):

                    # I appended age.
                    location_group[loc].append(rec["age"])

        # I returned statistics.
        return {k: self._ages_stats(v) for k, v in location_group.items()}

    # I counted dietary habits for stroke vs non-stroke.
    def diet_counts(self):

        # I initialized counters.
        stroke_yes = Counter()
        stroke_no = Counter()

        # I iterated through dataset.
        for row in self.dataset_bundle:

            # I extracted diet type.
            diet = row.get("dietary_habits")

            # I updated stroke counts.
            if row.get("stroke_occurrence") == 1:
                stroke_yes[diet] += 1
            else:
                stroke_no[diet] += 1

        # I returned results.
        return {"stroke": dict(stroke_yes), "no_stroke": dict(stroke_no)}

    # I filtered records with hypertension and stroke.
    def hypertension_and_stroke(self):

        # I returned filtered records.
        return [
            r for r in self.dataset_bundle
            if r.get("hypertension") == 1 and r.get("stroke_occurrence") == 1
        ]

    # I filtered records with heart disease and stroke.
    def heart_disease_and_stroke(self):

        # I returned filtered records.
        return [
            r for r in self.dataset_bundle
            if r.get("heart_disease") == 1 and r.get("stroke_occurrence") == 1
        ]

    # I compared sleep patterns.
    def sleep_comparison(self):

        # I initialized lists.
        stroke_sleep = []
        non_stroke_sleep = []

        # I iterated through dataset.
        for r in self.dataset_bundle:

            # I checked numeric sleep values.
            if isinstance(r.get("sleep_hours"), (int, float)):

                # I grouped based on stroke.
                if r.get("stroke_occurrence") == 1:
                    stroke_sleep.append(r["sleep_hours"])
                else:
                    non_stroke_sleep.append(r["sleep_hours"])

        # I returned average sleep values.
        return {
            "stroke_avg_sleep": self.stats_helper.calculate_mean(stroke_sleep),
            "non_stroke_avg_sleep": self.stats_helper.calculate_mean(non_stroke_sleep)
        }

    # I implemented flexible filtering.
    def flexible_filter(self, age_range=None, gender=None, smoking=None, region=None):

        # I initialized output list.
        filtered_output = []

        # I iterated through dataset.
        for rec in self.dataset_bundle:

            # I applied age filter.
            if age_range:
                if not (age_range[0] <= rec.get("age", 0) <= age_range[1]):
                    continue

            # I applied gender filter.
            if gender and rec.get("gender") != gender.lower():
                continue

            # I applied smoking filter.
            if smoking and rec.get("smoking_status") != smoking.lower():
                continue

            # I applied region filter.
            if region and rec.get("region") != region.lower():
                continue

            # I appended valid record.
            filtered_output.append(rec)

        # I returned filtered data.
        return filtered_output

    # I categorized stroke risk.
    def risk_categories(self):

        # I initialized counters.
        low = medium = high = 0

        # I calculated total records.
        total = len(self.dataset_bundle)

        # I iterated through dataset.
        for r in self.dataset_bundle:

            # I retrieved risk score.
            score = r.get("stroke_risk_score", 0)

            # I categorized risk.
            if score < 30:
                low += 1
            elif score < 70:
                medium += 1
            else:
                high += 1

        # I returned counts and percentages.
        return {
            "Low": (low, round(low / total * 100, 2)),
            "Medium": (medium, round(medium / total * 100, 2)),
            "High": (high, round(high / total * 100, 2))
        }

    # I summarized data region-wise.
    def regional_summary(self):

        # I initialized region container.
        region_data = {}

        # I iterated through dataset.
        for r in self.dataset_bundle:

            # I extracted region.
            region_key = r.get("region")

            # I initialized region if not present.
            if region_key not in region_data:
                region_data[region_key] = {"age": [], "bmi": [], "glucose": [], "stroke": []}

            # I appended numeric values.
            if isinstance(r.get("age"), (int, float)):
                region_data[region_key]["age"].append(r["age"])

            if isinstance(r.get("bmi"), (int, float)):
                region_data[region_key]["bmi"].append(r["bmi"])

            if isinstance(r.get("average_glucose_level"), (int, float)):
                region_data[region_key]["glucose"].append(r["average_glucose_level"])

            # I appended stroke occurrence.
            region_data[region_key]["stroke"].append(r.get("stroke_occurrence", 0))

        # I initialized final summary.
        final_summary = {}

        # I computed statistics for each region.
        for reg, vals in region_data.items():

            # I calculated stroke rate.
            stroke_rate = sum(vals["stroke"]) / len(vals["stroke"]) if vals["stroke"] else 0

            # I stored summary values.
            final_summary[reg] = {
                "avg_age": self.stats_helper.calculate_mean(vals["age"]),
                "avg_bmi": self.stats_helper.calculate_mean(vals["bmi"]),
                "avg_glucose": self.stats_helper.calculate_mean(vals["glucose"]),
                "stroke_rate": round(stroke_rate, 2)
            }

        # I returned final summary.
        return final_summary