# -*- coding: utf-8 -*-
"""statistics_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lM0kELekES_6wG6JeCMwGHiuu7xQmosK

# statistics_module.py
"""

# I imported the math module so that I could use mathematical functions such as square root for statistical calculations.
import math

# I imported the Counter class to efficiently calculate frequency counts, which was useful for computing the mode.
from collections import Counter

# I defined a class to perform statistical analysis on dataset records.
class StatisticalAnalyzer:

    # I defined the constructor to initialize the StatisticalAnalyzer object.
    # I accepted dataset records so that statistical computations could be performed on them.
    def __init__(self, dataset_records):

        # I stored the dataset records as an instance variable for reuse across all methods.
        self.dataset_records = dataset_records

    # I defined a method to extract only numeric values for a given feature.
    # I ensured that non-numeric and missing values were excluded.
    def extract_numeric_values(self, feature_key):

        # I initialized an empty list to store numeric values.
        numeric_collection = []

        # I normalized the feature name to ensure consistency with dataset keys.
        # I removed spaces, converted to lowercase, and replaced spaces with underscores.
        feature_key = feature_key.strip().lower().replace(" ", "_")

        # I iterated through each record in the dataset.
        for entry in self.dataset_records:

            # I safely retrieved the value using the feature key.
            value = entry.get(feature_key)

            # I checked whether the value was numeric (integer or float).
            if isinstance(value, (int, float)):

                # I appended valid numeric values to the collection.
                numeric_collection.append(value)

        # I returned the filtered list of numeric values.
        return numeric_collection

    # I defined a method to calculate the mean (average).
    def calculate_mean(self, values_list):

        # I checked if the list was empty to avoid division by zero.
        if not values_list:
            return None

        # I calculated the mean as sum divided by count.
        return sum(values_list) / len(values_list)

    # I defined a method to calculate the median.
    def calculate_median(self, values_list):

        # I handled empty input cases.
        if not values_list:
            return None

        # I sorted the values in ascending order.
        sorted_values = sorted(values_list)

        # I calculated the total number of elements.
        length = len(sorted_values)

        # I determined the middle index.
        mid_index = length // 2

        # I checked if the number of elements was even.
        if length % 2 == 0:

            # I calculated the median as the average of two middle values.
            return (sorted_values[mid_index - 1] + sorted_values[mid_index]) / 2

        else:
            # I returned the middle value directly for odd-length lists.
            return sorted_values[mid_index]

    # I defined a method to calculate the mode (most frequent value).
    def calculate_mode(self, values_list):

        # I handled empty input cases.
        if not values_list:
            return None

        # I created a Counter object to count occurrences of values.
        frequency_counter = Counter(values_list)

        # I retrieved the most common value.
        return frequency_counter.most_common(1)[0][0]

    # I defined a method to calculate the minimum value.
    def calculate_minimum(self, values_list):

        # I handled empty input cases.
        if not values_list:
            return None

        # I returned the smallest value.
        return min(values_list)

    # I defined a method to calculate the maximum value.
    def calculate_maximum(self, values_list):

        # I handled empty input cases.
        if not values_list:
            return None

        # I returned the largest value.
        return max(values_list)

    # I defined a method to calculate the range.
    def calculate_range(self, values_list):

        # I handled empty input cases.
        if not values_list:
            return None

        # I calculated the range as max minus min.
        return self.calculate_maximum(values_list) - self.calculate_minimum(values_list)

    # I defined a method to calculate variance (data dispersion).
    def calculate_variance(self, values_list):

        # I handled empty input cases.
        if not values_list:
            return None

        # I calculated the mean value.
        mean_value = self.calculate_mean(values_list)

        # I computed squared differences from the mean.
        squared_differences = [(x - mean_value) ** 2 for x in values_list]

        # I calculated variance as the average of squared differences.
        return sum(squared_differences) / len(values_list)

    # I defined a method to calculate standard deviation.
    def calculate_standard_deviation(self, values_list):

        # I handled empty input cases.
        if not values_list:
            return None

        # I calculated variance first.
        variance_value = self.calculate_variance(values_list)

        # I computed the square root of variance.
        return math.sqrt(variance_value)

    # I defined a method to compute all descriptive statistics for a feature.
    def get_descriptive_statistics(self, feature_key):

        # I extracted numeric values for the given feature.
        numeric_values = self.extract_numeric_values(feature_key)

        # I checked if no numeric values were found.
        if not numeric_values:

            # I returned an error message in dictionary format.
            return {"Error": f"No numeric data found for feature: {feature_key}"}

        # I created a dictionary to store all statistical results.
        statistics_result = {

            # I calculated and rounded the mean.
            "mean": round(self.calculate_mean(numeric_values), 2),

            # I calculated and rounded the median.
            "median": round(self.calculate_median(numeric_values), 2),

            # I calculated the mode.
            "mode": self.calculate_mode(numeric_values),

            # I retrieved the minimum value.
            "minimum": self.calculate_minimum(numeric_values),

            # I retrieved the maximum value.
            "maximum": self.calculate_maximum(numeric_values),

            # I calculated the range.
            "range": self.calculate_range(numeric_values),

            # I calculated and rounded the variance.
            "variance": round(self.calculate_variance(numeric_values), 2),

            # I calculated and rounded the standard deviation.
            "standard_deviation": round(self.calculate_standard_deviation(numeric_values), 2)
        }

        # I returned the computed statistical results.
        return statistics_result