# -*- coding: utf-8 -*-
"""user_interface_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lM0kELekES_6wG6JeCMwGHiuu7xQmosK

# user_interface_module.py
"""

# I imported tkinter to build the graphical user interface.
import tkinter as tk

# I imported ttk for advanced widgets, messagebox for alerts, and filedialog for file operations.
from tkinter import ttk, messagebox, filedialog

# I defined a class to manage the Health Analytics User Interface.
class HealthAnalyticsUI:

    # I defined the constructor to initialize the UI components.
    def __init__(self, root_window, dataset_input):

        # I stored the main window reference.
        self.root_window = root_window

        # I set the title of the application window.
        self.root_window.title("Patient Health Analytics System")

        # I defined the window size.
        self.root_window.geometry("900x600")

        # I initialized the query processor module.
        self.query_engine = QueryProcessor(dataset_input)

        # I initialized the statistical analyzer module.
        self.stats_engine = StatisticalAnalyzer(dataset_input)

        # I created the main layout of the UI.
        self.create_layout()

    # I defined a method to create and organize all UI components.
    def create_layout(self):

        # I created a top frame for the header.
        top_frame = tk.Frame(self.root_window, bg="#2c3e50")

        # I packed the frame horizontally.
        top_frame.pack(fill="x")

        # I created a label for the dashboard title.
        tk.Label(
            top_frame,
            text="Health Analytics Dashboard",
            bg="#2c3e50",
            fg="white",
            font=("Arial", 16, "bold")
        ).pack(pady=10)

        # I created a dropdown (combobox) for selecting queries.
        self.query_selector = ttk.Combobox(self.root_window, width=60)

        # I assigned available query options.
        self.query_selector["values"] = [
            "Smokers with Hypertension",
            "Heart Disease Stats",
            "Gender Hypertension Stroke",
            "Activity Based Stats",
            "Urban Rural Stroke",
            "Diet Counts",
            "Hypertension Stroke Patients",
            "Heart Disease Stroke Patients",
            "Sleep Comparison",
            "Flexible Filter",
            "Risk Categories",
            "Regional Summary",
            "Descriptive Statistics"
        ]

        # I displayed the dropdown.
        self.query_selector.pack(pady=10)

        # I bound selection event to input toggle function.
        self.query_selector.bind("<<ComboboxSelected>>", self.toggle_inputs)

        # I created a frame to hold user input fields.
        self.input_frame = tk.Frame(self.root_window)

        # I packed the input frame.
        self.input_frame.pack(pady=10)

        # I created label and entry for minimum age.
        tk.Label(self.input_frame, text="Min Age").grid(row=0, column=0)
        self.min_age_input = tk.Entry(self.input_frame)
        self.min_age_input.grid(row=0, column=1)

        # I created label and entry for maximum age.
        tk.Label(self.input_frame, text="Max Age").grid(row=1, column=0)
        self.max_age_input = tk.Entry(self.input_frame)
        self.max_age_input.grid(row=1, column=1)

        # I created label and dropdown for gender.
        tk.Label(self.input_frame, text="Gender").grid(row=0, column=2)
        self.gender_input = ttk.Combobox(self.input_frame, values=["male", "female", "other"])
        self.gender_input.grid(row=0, column=3)

        # I created label and dropdown for region.
        tk.Label(self.input_frame, text="Region").grid(row=1, column=2)
        self.region_input = ttk.Combobox(self.input_frame, values=["north", "south", "east", "west"])
        self.region_input.grid(row=1, column=3)

        # I created label and entry for feature input.
        tk.Label(self.input_frame, text="Feature").grid(row=2, column=0)
        self.feature_input = tk.Entry(self.input_frame)
        self.feature_input.grid(row=2, column=1)

        # I created a frame for buttons.
        button_frame = tk.Frame(self.root_window)

        # I packed the button frame.
        button_frame.pack(pady=10)

        # I created a button to execute queries.
        tk.Button(
            button_frame,
            text="Run Query",
            command=self.execute_query,
            bg="#27ae60",
            fg="white"
        ).grid(row=0, column=0, padx=5)

        # I created a button to export results.
        tk.Button(
            button_frame,
            text="Export CSV",
            command=self.export_results,
            bg="#2980b9",
            fg="white"
        ).grid(row=0, column=1, padx=5)

        # I created a button to clear output.
        tk.Button(
            button_frame,
            text="Clear",
            command=self.clear_output,
            bg="#c0392b",
            fg="white"
        ).grid(row=0, column=2, padx=5)

        # I created a button to exit the application.
        tk.Button(
            button_frame,
            text="Exit",
            command=self.root_window.quit
        ).grid(row=0, column=3, padx=5)

        # I created a text box to display output.
        self.output_box = tk.Text(self.root_window, height=20, width=100)

        # I packed the output box.
        self.output_box.pack(pady=10)

        # I initialized a variable to store the latest result.
        self.latest_result = None

    # I defined a method to enable all input fields.
    def toggle_inputs(self, event=None):

        # I enabled minimum age input.
        self.min_age_input.config(state="normal")

        # I enabled maximum age input.
        self.max_age_input.config(state="normal")

        # I enabled gender dropdown.
        self.gender_input.config(state="normal")

        # I enabled region dropdown.
        self.region_input.config(state="normal")

        # I enabled feature input.
        self.feature_input.config(state="normal")

    # I defined a method to execute the selected query.
    def execute_query(self):

        # I used try block to handle input and runtime errors.
        try:

            # I retrieved selected query.
            selected_query = self.query_selector.get()

            # I matched query and executed corresponding method.
            if selected_query == "Smokers with Hypertension":
                result_data = self.query_engine.smokers_with_hypertension()

            elif selected_query == "Heart Disease Stats":
                result_data = self.query_engine.heart_disease_stats()

            elif selected_query == "Gender Hypertension Stroke":
                result_data = self.query_engine.gender_hypertension_stroke()

            elif selected_query == "Activity Based Stats":
                result_data = self.query_engine.activity_based_stats()

            elif selected_query == "Urban Rural Stroke":
                result_data = self.query_engine.urban_rural_stroke()

            elif selected_query == "Diet Counts":
                result_data = self.query_engine.diet_counts()

            elif selected_query == "Hypertension Stroke Patients":
                result_data = self.query_engine.hypertension_and_stroke()

            elif selected_query == "Heart Disease Stroke Patients":
                result_data = self.query_engine.heart_disease_and_stroke()

            elif selected_query == "Sleep Comparison":
                result_data = self.query_engine.sleep_comparison()

            elif selected_query == "Flexible Filter":

                # I extracted age inputs safely.
                min_age = int(self.min_age_input.get()) if self.min_age_input.get() else None
                max_age = int(self.max_age_input.get()) if self.max_age_input.get() else None

                # I retrieved gender and region inputs.
                gender = self.gender_input.get()
                region = self.region_input.get()

                # I executed flexible filtering.
                result_data = self.query_engine.flexible_filter(
                    age_range=(min_age, max_age) if min_age and max_age else None,
                    gender=gender.lower() if gender else None,
                    region=region.lower() if region else None
                )

            elif selected_query == "Risk Categories":
                result_data = self.query_engine.risk_categories()

            elif selected_query == "Regional Summary":
                result_data = self.query_engine.regional_summary()

            elif selected_query == "Descriptive Statistics":

                # I retrieved feature input.
                feature = self.feature_input.get()

                # I computed descriptive statistics.
                result_data = self.stats_engine.get_descriptive_statistics(feature)

            else:

                # I displayed error for invalid selection.
                messagebox.showerror("Error", "Please select a valid option")
                return

            # I stored latest result.
            self.latest_result = result_data

            # I displayed output.
            self.display_output(result_data)

        # I handled invalid numeric input errors.
        except ValueError:
            messagebox.showerror("Input Error", "Please enter valid numeric values")

        # I handled unexpected errors.
        except Exception as err:
            messagebox.showerror("Error", str(err))

    # I defined a method to display output in the text box.
    def display_output(self, data):

        # I cleared previous output.
        self.output_box.delete("1.0", tk.END)

        # I handled dictionary output.
        if isinstance(data, dict):
            for key, value in data.items():
                self.output_box.insert(tk.END, f"{key} → {value}\n")

        # I handled list output.
        elif isinstance(data, list):
            for item in data[:50]:
                self.output_box.insert(tk.END, f"{item}\n")

    # I defined a method to export results.
    def export_results(self):

        # I checked if there was data to export.
        if not self.latest_result:
            messagebox.showerror("Error", "No data to export")
            return

        # I opened file dialog.
        file_path = filedialog.asksaveasfilename(defaultextension=".csv")

        # I saved file if path selected.
        if file_path:
            self.query_engine.save_to_csv(self.latest_result, file_path)
            messagebox.showinfo("Success", "File exported successfully")

    # I defined a method to clear output.
    def clear_output(self):

        # I cleared text box content.
        self.output_box.delete("1.0", tk.END)